# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99e0254eeb194e426b7a299626938be24d8a837127a6169de31e6ff9d1f2f9fbd25d6d3cd4b18222e515c19805babfaed5ae39085bf77d74d03cf8113c2716f7

test:
  secret_key_base: 4e9d2cdd9978ba4ae919315213fc71862ee37eb378a83e34b03ebdc451659481d463c776eb36dc338714196c6705e63c3e20190eb67835b2da829368d2e9325e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
